version: '3'

services:
  pi-relay-controll:
    container_name: pi-relay-control
    build: .
    ports:
      - "8080:8080"
    volumes:
      - "/sys:/sys"
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
    environment:
      - RELAY_PIN=18  # Change 18 to your GPIO pin number
    restart: unless-stopped
    privileged: true
