version: '3'

services:
  pi-relay-controll:
    container_name: pi-relay-control
    build: .
    ports:
      - "8081:8080"
    volumes:
      - "/sys:/sys"
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
    restart: unless-stopped
    privileged: true
